name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ant-version: ["1.7.0", "1.10.12"]
        java-version: ["11", "17", "19"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: "maven"
      - run: mvn -Dant.version=${{ matrix.ant-version }} compile package
  dist:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: "maven"
      - run: mvn compile package
      - uses: actions/upload-artifact@v3
        with:
          name: mergeservices.jar
          path: target/mergeservices*.jar